name: CI

on:
  workflow_call:

permissions:
  contents: read

jobs:
  parallel-tasks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ["ci", "typecheck", "test:ui", "test:server", "test:integration"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-deps
      - run: cp .env.sample .env
      - run: pnpm run ${{ matrix.task }}

  # e2e:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ./.github/actions/setup-node-deps
  #     - run: npx playwright install
  #     - run: cp .env.sample .env
  #     - run: |
  #         docker compose up -d
  #         ./scripts/setup-garage.sh
  #         pnpm run prisma:migrate:dev
  #         pnpm run prisma:seed
  #         pnpm run test:e2e
  #         docker compose down
